batch64:
	python main-original.py --epoch 1 --gpu=0 -b 64 -a alexnet ~/data/imagenette2
	python main-original.py --epoch 1 --gpu=0 -b 64 -a densenet121 ~/data/imagenette2
	python main-original.py --epoch 1 --gpu=0 -b 64 -a densenet161 ~/data/imagenette2
	python main-original.py --epoch 1 --gpu=0 -b 64 -a densenet169 ~/data/imagenette2
	python main-original.py --epoch 1 --gpu=0 -b 64 -a densenet201 ~/data/imagenette2
	python main-original.py --epoch 1 --gpu=0 -b 64 -a resnet101 ~/data/imagenette2
	python main-original.py --epoch 1 --gpu=0 -b 64 -a resnet152 ~/data/imagenette2
	python main-original.py --epoch 1 --gpu=0 -b 64 -a resnet18 ~/data/imagenette2
	python main-original.py --epoch 1 --gpu=0 -b 64 -a resnet34 ~/data/imagenette2
	python main-original.py --epoch 1 --gpu=0 -b 64 -a resnet50 ~/data/imagenette2
	python main-original.py --epoch 1 --gpu=0 -b 64 -a squeezenet1_0 ~/data/imagenette2
	python main-original.py --epoch 1 --gpu=0 -b 64 -a squeezenet1_1 ~/data/imagenette2
	python main-original.py --epoch 1 --gpu=0 -b 64 -a vgg11 ~/data/imagenette2
	python main-original.py --epoch 1 --gpu=0 -b 64 -a vgg11_bn ~/data/imagenette2
	python main-original.py --epoch 1 --gpu=0 -b 64 -a vgg13 ~/data/imagenette2
	python main-original.py --epoch 1 --gpu=0 -b 64 -a vgg13_bn ~/data/imagenette2
	python main-original.py --epoch 1 --gpu=0 -b 64 -a vgg16 ~/data/imagenette2
	python main-original.py --epoch 1 --gpu=0 -b 64 -a vgg16_bn ~/data/imagenette2
	python main-original.py --epoch 1 --gpu=0 -b 64 -a vgg19 ~/data/imagenette2
	python main-original.py --epoch 1 --gpu=0 -b 64 -a vgg19_bn ~/data/imagenette2
	
batch128:
	python main-original.py --epoch 1 --gpu=0 -b 128 -a alexnet ~/data/imagenette2
	python main-original.py --epoch 1 --gpu=0 -b 128 -a densenet121 ~/data/imagenette2
	python main-original.py --epoch 1 --gpu=0 -b 128 -a densenet161 ~/data/imagenette2
	python main-original.py --epoch 1 --gpu=0 -b 128 -a densenet169 ~/data/imagenette2
	python main-original.py --epoch 1 --gpu=0 -b 128 -a densenet201 ~/data/imagenette2
	python main-original.py --epoch 1 --gpu=0 -b 128 -a resnet101 ~/data/imagenette2
	python main-original.py --epoch 1 --gpu=0 -b 128 -a resnet152 ~/data/imagenette2
	python main-original.py --epoch 1 --gpu=0 -b 128 -a resnet18 ~/data/imagenette2
	python main-original.py --epoch 1 --gpu=0 -b 128 -a resnet34 ~/data/imagenette2
	python main-original.py --epoch 1 --gpu=0 -b 128 -a resnet50 ~/data/imagenette2
	python main-original.py --epoch 1 --gpu=0 -b 128 -a squeezenet1_0 ~/data/imagenette2
	python main-original.py --epoch 1 --gpu=0 -b 128 -a squeezenet1_1 ~/data/imagenette2
	python main-original.py --epoch 1 --gpu=0 -b 128 -a vgg11 ~/data/imagenette2
	python main-original.py --epoch 1 --gpu=0 -b 128 -a vgg11_bn ~/data/imagenette2
	python main-original.py --epoch 1 --gpu=0 -b 128 -a vgg13 ~/data/imagenette2
	python main-original.py --epoch 1 --gpu=0 -b 128 -a vgg13_bn ~/data/imagenette2
	python main-original.py --epoch 1 --gpu=0 -b 128 -a vgg16 ~/data/imagenette2
	python main-original.py --epoch 1 --gpu=0 -b 128 -a vgg16_bn ~/data/imagenette2
	python main-original.py --epoch 1 --gpu=0 -b 128 -a vgg19 ~/data/imagenette2
	python main-original.py --epoch 1 --gpu=0 -b 128 -a vgg19_bn ~/data/imagenette2


run: batch64 batch128

.PHONY: run
